In [1]:
# Ячейка 1: Импорт библиотек
import numpy as np

In [2]:
# Ячейка 2: Создание массивов
# Из обычных списков
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)

list_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d)

# С использованием функций
zeros_arr = np.zeros(4)
ones_arr = np.ones((2, 3))
arange_arr = np.arange(0, 10, 2)

print("1D массив:", array_1d)
print("2D массив:\n", array_2d)
print("Zeros:", zeros_arr)
print("Ones:\n", ones_arr)
print("Arange:", arange_arr)

1D массив: [1 2 3 4 5]
2D массив:
 [[1 2 3]
 [4 5 6]]
Zeros: [0. 0. 0. 0.]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]


In [3]:
# Ячейка 3: Атрибуты массивов
print("Форма 2D массива:", array_2d.shape)
print("Тип данных:", array_2d.dtype)
print("Размерность:", array_2d.ndim)
print("Количество элементов:", array_2d.size)

Форма 2D массива: (2, 3)
Тип данных: int64
Размерность: 2
Количество элементов: 6


In [4]:
# Ячейка 4: Индексирование и срезы
# Одномерный массив
arr = np.array([10, 20, 30, 40, 50])
print("Элемент с индексом 2:", arr[2])
print("Срез [1:4]:", arr[1:4])

# Двумерный массив
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Элемент [1,2]:", matrix[1, 2])
print("Первые 2 строки:\n", matrix[:2, :])

Элемент с индексом 2: 30
Срез [1:4]: [20 30 40]
Элемент [1,2]: 6
Первые 2 строки:
 [[1 2 3]
 [4 5 6]]


In [5]:
# Ячейка 5: Векторные операции и статистика
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Сложение:", a + b)
print("Умножение:", a * b)
print("Среднее значение a:", np.mean(a))
print("Сумма всех элементов b:", np.sum(b))

Сложение: [5 7 9]
Умножение: [ 4 10 18]
Среднее значение a: 2.0
Сумма всех элементов b: 15
