In [1]:
import numpy as np

включение библиотеки numpy

In [2]:
a = np.array([[2,3],[3,2]])
a

array([[2, 3],
       [3, 2]])

создан двумерный массив из обычного списка

In [3]:
a.shape

(2, 2)

размер массива а

In [4]:
b = np.zeros((3,2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

создан двумерный массив нулей

In [5]:
c = np.ones((5,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

создан двумерный массив единиц

In [6]:
d = np.arange(2,10,4)
d

array([2, 6])

создан одномерный массив последовательностей

In [7]:
e = np.empty((2,3,4))
e

array([[[7.49984198e-067, 1.04914861e-153, 1.94918966e-153,
         6.37115242e-067],
        [4.17202692e-057, 2.11100962e-052, 2.59027896e-144,
         7.79952704e-143],
        [5.81186265e+294, 2.75985030e+296, 1.04011364e-314,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]]])

создан трехмерный массив из мусора в памяти

In [8]:
e.shape

(2, 3, 4)

размер последнего массива е

In [9]:
e.dtype

dtype('float64')

тип данных последнего массива е

In [10]:
d.dtype

dtype('int64')

тип данных массива d отличается от е

In [11]:
b = np.array([[ 0,  1,  2,  3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

пересоздам массив б для дальнейших действий с ним 

In [12]:
b[2,3]

np.int64(23)

поиск элемента по индексу в двумерном массиве

In [13]:
b[[2,3],[2,2]]

array([22, 32])

взял во второй строке второй элемент и в третей строке - третий (по индексам)

In [14]:
b[1:4,1:3]

array([[11, 12],
       [21, 22],
       [31, 32]])

вывел серединку массива

In [15]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [16]:
b3 = b[3]
b3

array([30, 31, 32, 33])

сделал из четвертой строки массива b отдельный массив b3

In [17]:
b[:,1]

array([ 1, 11, 21, 31, 41])

вывел второй стобец массива b

In [18]:
a

array([[2, 3],
       [3, 2]])

In [19]:
c=np.array([[1,2],[4,5]])
c

array([[1, 2],
       [4, 5]])

In [20]:
a+c

array([[3, 5],
       [7, 7]])

поэлементное сложение массивов

In [21]:
a.sum()

np.int64(10)

сложение элементов массива а 

In [22]:
a*c

array([[ 2,  6],
       [12, 10]])

поэлементное умножение массивов

In [23]:
b + 2

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45]])

сложение элементов массива со скаляром

In [24]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [25]:
b.max(axis=0)

array([40, 41, 42, 43])

максимальные значения по столбцам

In [26]:
b.min(axis=1)

array([ 0, 10, 20, 30, 40])

минимальные значения по строкам

In [27]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [28]:
a.shape

(2, 2, 3)

In [29]:
a[0,1,1]

np.int64(12)

извлечение элемента массива по индексу

In [30]:
a.ravel()

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [31]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

ravel выводит массив в одномерном виде, но не изменяет его 

In [32]:
a.reshape((3,4))

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

In [33]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [34]:
a.shape = (3,4)

In [35]:
a

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

shape меняет сам массив, reshape - не меняет

In [36]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [37]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [38]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
np.hstack((b,a))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

массивы можно объединять по вертикали и горизонтали

In [40]:
a = np.arange(12).reshape((2, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [41]:
np.hsplit(a,6)

[array([[0],
        [6]]),
 array([[1],
        [7]]),
 array([[2],
        [8]]),
 array([[3],
        [9]]),
 array([[ 4],
        [10]]),
 array([[ 5],
        [11]])]

разрезать массив на 6 равных частей по столбцам

In [42]:
np.hsplit(a,(2,5))

[array([[0, 1],
        [6, 7]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10]]),
 array([[ 5],
        [11]])]

обрезал по 2 и 5 столбцам

In [43]:
import random
import numpy.random as rand

модули для работы со случайными (псевдослучайными) числами

In [44]:
a = np.random.randint(1,5,(2,3,3))
a

array([[[1, 3, 3],
        [1, 4, 3],
        [1, 4, 2]],

       [[2, 1, 4],
        [1, 2, 3],
        [2, 2, 2]]], dtype=int32)

трехмерный массив рандомных чисел от 1 до 4

In [45]:
np.random.shuffle(a)
a

array([[[1, 3, 3],
        [1, 4, 3],
        [1, 4, 2]],

       [[2, 1, 4],
        [1, 2, 3],
        [2, 2, 2]]], dtype=int32)

можно перемешать массив

In [46]:
np.mean(a)

np.float64(2.2777777777777777)

среднее значение для всего массива

In [47]:
np.mean(a,axis=1)

array([[1.        , 3.66666667, 2.66666667],
       [1.66666667, 1.66666667, 3.        ]])

In [48]:
a

array([[[1, 3, 3],
        [1, 4, 3],
        [1, 4, 2]],

       [[2, 1, 4],
        [1, 2, 3],
        [2, 2, 2]]], dtype=int32)

среднее значение для каждой строки